{
  "dataType": "CVE_RECORD",
  "dataVersion": "5.1",
  "cveMetadata": {
    "cveId": "CVE-2025-27510",
    "assignerOrgId": "a0819718-46f1-4df5-94e2-005712e83aaa",
    "state": "PUBLISHED",
    "assignerShortName": "GitHub_M",
    "dateReserved": "2025-02-26T18:11:52.306Z",
    "datePublished": "2025-03-04T21:48:12.688Z",
    "dateUpdated": "2025-03-04T21:48:12.688Z"
  },
  "containers": {
    "cna": {
      "title": "RCE in the package conda-forge-metadata",
      "problemTypes": [
        {
          "descriptions": [
            {
              "cweId": "CWE-829",
              "lang": "en",
              "description": "CWE-829: Inclusion of Functionality from Untrusted Control Sphere",
              "type": "CWE"
            }
          ]
        }
      ],
      "metrics": [
        {
          "cvssV4_0": {
            "attackVector": "NETWORK",
            "attackComplexity": "LOW",
            "attackRequirements": "NONE",
            "privilegesRequired": "NONE",
            "userInteraction": "NONE",
            "vulnConfidentialityImpact": "HIGH",
            "vulnIntegrityImpact": "HIGH",
            "vulnAvailabilityImpact": "HIGH",
            "subConfidentialityImpact": "NONE",
            "subIntegrityImpact": "NONE",
            "subAvailabilityImpact": "NONE",
            "baseScore": 9.3,
            "baseSeverity": "CRITICAL",
            "vectorString": "CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N",
            "version": "4.0"
          }
        }
      ],
      "references": [
        {
          "name": "https://github.com/conda-forge/conda-forge-metadata/security/advisories/GHSA-vwfh-m3q7-9jpw",
          "tags": [
            "x_refsource_CONFIRM"
          ],
          "url": "https://github.com/conda-forge/conda-forge-metadata/security/advisories/GHSA-vwfh-m3q7-9jpw"
        },
        {
          "name": "https://github.com/conda-forge/conda-forge-metadata/blob/799aee36b21ee06289d73d57838b28201f5a57af/pyproject.toml#L28",
          "tags": [
            "x_refsource_MISC"
          ],
          "url": "https://github.com/conda-forge/conda-forge-metadata/blob/799aee36b21ee06289d73d57838b28201f5a57af/pyproject.toml#L28"
        }
      ],
      "affected": [
        {
          "vendor": "conda-forge",
          "product": "conda-forge-metadata",
          "versions": [
            {
              "version": "<=  0.4.1",
              "status": "affected"
            }
          ]
        }
      ],
      "providerMetadata": {
        "orgId": "a0819718-46f1-4df5-94e2-005712e83aaa",
        "shortName": "GitHub_M",
        "dateUpdated": "2025-03-04T21:48:12.688Z"
      },
      "descriptions": [
        {
          "lang": "en",
          "value": "conda-forge-metadata provides programatic access to conda-forge's metadata. conda-forge-metadata uses an optional dependency - \"conda-oci-mirror\" which was neither present on the PyPi repository nor registered by any entity. If conda-oci-mirror is taken over by a threat actor, it can result in remote code execution."
        }
      ],
      "source": {
        "advisory": "GHSA-vwfh-m3q7-9jpw",
        "discovery": "UNKNOWN"
      }
    }
  }
}