{
  "dataType": "CVE_RECORD",
  "dataVersion": "5.1",
  "cveMetadata": {
    "cveId": "CVE-2024-45347",
    "assignerOrgId": "b57733aa-7326-4f07-8e09-0be8e0df1909",
    "state": "PUBLISHED",
    "assignerShortName": "Xiaomi",
    "dateReserved": "2024-08-28T02:24:34.837Z",
    "datePublished": "2025-06-23T09:34:38.676Z",
    "dateUpdated": "2025-06-23T09:34:41.202Z"
  },
  "containers": {
    "cna": {
      "affected": [
        {
          "defaultStatus": "unaffected",
          "product": "Xiaomi Mi Connect Service",
          "vendor": "Xiaomi",
          "versions": [
            {
              "status": "affected",
              "version": "Xiaomi Mi Connect Service3.1.895.10"
            }
          ]
        }
      ],
      "datePublic": "2025-02-20T09:25:00.000Z",
      "descriptions": [
        {
          "lang": "en",
          "supportingMedia": [
            {
              "base64": false,
              "type": "text/html",
              "value": "An unauthorized access vulnerability exists in the Xiaomi Mi Connect Service APP. The vulnerability is caused by the validation logic is flawed and can be exploited by attackers to Unauthorized access to the victim’s device.   <br>"
            }
          ],
          "value": "An unauthorized access vulnerability exists in the Xiaomi Mi Connect Service APP. The vulnerability is caused by the validation logic is flawed and can be exploited by attackers to Unauthorized access to the victim’s device."
        }
      ],
      "impacts": [
        {
          "capecId": "CAPEC-151",
          "descriptions": [
            {
              "lang": "en",
              "value": "CAPEC-151 Identity Spoofing"
            }
          ]
        }
      ],
      "metrics": [
        {
          "cvssV3_1": {
            "attackComplexity": "LOW",
            "attackVector": "ADJACENT_NETWORK",
            "availabilityImpact": "HIGH",
            "baseScore": 9.6,
            "baseSeverity": "CRITICAL",
            "confidentialityImpact": "HIGH",
            "integrityImpact": "HIGH",
            "privilegesRequired": "NONE",
            "scope": "CHANGED",
            "userInteraction": "NONE",
            "vectorString": "CVSS:3.1/AV:A/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H",
            "version": "3.1"
          },
          "format": "CVSS",
          "scenarios": [
            {
              "lang": "en",
              "value": "GENERAL"
            }
          ]
        }
      ],
      "problemTypes": [
        {
          "descriptions": [
            {
              "cweId": "CWE-287",
              "description": "CWE-287 Improper Authentication",
              "lang": "en",
              "type": "CWE"
            }
          ]
        }
      ],
      "providerMetadata": {
        "orgId": "b57733aa-7326-4f07-8e09-0be8e0df1909",
        "shortName": "Xiaomi",
        "dateUpdated": "2025-06-23T09:34:41.202Z"
      },
      "references": [
        {
          "url": "https://trust.mi.com/zh-CN/misrc/bulletins/advisory?cveId=548"
        }
      ],
      "source": {
        "discovery": "UNKNOWN"
      },
      "title": "Mi Connect Service APP protocol flaws lead to unauthorized access",
      "x_generator": {
        "engine": "Vulnogram 0.1.0-dev"
      }
    }
  }
}