{
  "dataType": "CVE_RECORD",
  "dataVersion": "5.1",
  "cveMetadata": {
    "cveId": "CVE-2025-32434",
    "assignerOrgId": "a0819718-46f1-4df5-94e2-005712e83aaa",
    "state": "PUBLISHED",
    "assignerShortName": "GitHub_M",
    "dateReserved": "2025-04-08T10:54:58.368Z",
    "datePublished": "2025-04-18T15:48:18.851Z",
    "dateUpdated": "2025-04-18T16:06:51.966Z"
  },
  "containers": {
    "cna": {
      "title": "PyTorch: `torch.load` with `weights_only=True` leads to remote code execution",
      "problemTypes": [
        {
          "descriptions": [
            {
              "cweId": "CWE-502",
              "lang": "en",
              "description": "CWE-502: Deserialization of Untrusted Data",
              "type": "CWE"
            }
          ]
        }
      ],
      "metrics": [
        {
          "cvssV4_0": {
            "attackVector": "NETWORK",
            "attackComplexity": "LOW",
            "attackRequirements": "NONE",
            "privilegesRequired": "NONE",
            "userInteraction": "NONE",
            "vulnConfidentialityImpact": "HIGH",
            "vulnIntegrityImpact": "HIGH",
            "vulnAvailabilityImpact": "HIGH",
            "subConfidentialityImpact": "NONE",
            "subIntegrityImpact": "NONE",
            "subAvailabilityImpact": "NONE",
            "baseScore": 9.3,
            "baseSeverity": "CRITICAL",
            "vectorString": "CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N",
            "version": "4.0"
          }
        }
      ],
      "references": [
        {
          "name": "https://github.com/pytorch/pytorch/security/advisories/GHSA-53q9-r3pm-6pq6",
          "tags": [
            "x_refsource_CONFIRM"
          ],
          "url": "https://github.com/pytorch/pytorch/security/advisories/GHSA-53q9-r3pm-6pq6"
        }
      ],
      "affected": [
        {
          "vendor": "pytorch",
          "product": "pytorch",
          "versions": [
            {
              "version": "< 2.6.0",
              "status": "affected"
            }
          ]
        }
      ],
      "providerMetadata": {
        "orgId": "a0819718-46f1-4df5-94e2-005712e83aaa",
        "shortName": "GitHub_M",
        "dateUpdated": "2025-04-18T15:48:18.851Z"
      },
      "descriptions": [
        {
          "lang": "en",
          "value": "PyTorch is a Python package that provides tensor computation with strong GPU acceleration and deep neural networks built on a tape-based autograd system. In version 2.5.1 and prior, a Remote Command Execution (RCE) vulnerability exists in PyTorch when loading a model using torch.load with weights_only=True. This issue has been patched in version 2.6.0."
        }
      ],
      "source": {
        "advisory": "GHSA-53q9-r3pm-6pq6",
        "discovery": "UNKNOWN"
      }
    },
    "adp": [
      {
        "metrics": [
          {
            "other": {
              "type": "ssvc",
              "content": {
                "timestamp": "2025-04-18T16:06:40.000632Z",
                "id": "CVE-2025-32434",
                "options": [
                  {
                    "Exploitation": "none"
                  },
                  {
                    "Automatable": "yes"
                  },
                  {
                    "Technical Impact": "total"
                  }
                ],
                "role": "CISA Coordinator",
                "version": "2.0.3"
              }
            }
          }
        ],
        "title": "CISA ADP Vulnrichment",
        "providerMetadata": {
          "orgId": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
          "shortName": "CISA-ADP",
          "dateUpdated": "2025-04-18T16:06:51.966Z"
        }
      }
    ]
  }
}